USE [master]
GO

/****** Object:  Database [ParImpar]    Script Date: 14/11/2021 23:07:00 ******/
DROP DATABASE [ParImpar]
GO

/****** Object:  Database [ParImpar]    Script Date: 14/11/2021 23:07:00 ******/
CREATE DATABASE [ParImpar]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ParImpar', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ParImpar.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ParImpar_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ParImpar_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ParImpar].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ParImpar] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ParImpar] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ParImpar] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ParImpar] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ParImpar] SET ARITHABORT OFF 
GO

ALTER DATABASE [ParImpar] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ParImpar] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ParImpar] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ParImpar] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ParImpar] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ParImpar] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ParImpar] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ParImpar] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ParImpar] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ParImpar] SET  ENABLE_BROKER 
GO

ALTER DATABASE [ParImpar] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ParImpar] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ParImpar] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ParImpar] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ParImpar] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ParImpar] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ParImpar] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ParImpar] SET RECOVERY FULL 
GO

ALTER DATABASE [ParImpar] SET  MULTI_USER 
GO

ALTER DATABASE [ParImpar] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ParImpar] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ParImpar] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ParImpar] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ParImpar] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ParImpar] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ParImpar] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ParImpar] SET  READ_WRITE 
GO

